.\"     Title: vigedit
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 08/27/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "VIGEDIT" "1" "08/27/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
vigedit - Gedit plugins that enables Vi(m)-style key bindings for navigating documents.
.SH "SYNOPSIS"
Place the ViGedit distribution files in ~/\.gnome2/gedit/plugins\.
.sp
.SH "DESCRIPTION"
ViGedit gives the editor different modes, where each mode assign different actions to particular key combinations\.
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'explanation of the different bindings can be found here :
Bindings
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'An explanation of how to add a new mode can be found here :
Adding a mode
.RE
.SH "OPTIONS"
Your only option is to modify the source code\.
.sp
.SH "BUGS"
See the ViGedit distribution BUGS file for known bugs\.
.sp
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Warning
Undiscovered bugs might be present, which causes vigedit to wreak you car, eat all the food in your fridge or delete you Master thesis\. You have been warned\.
.sp
.SH "AUTHOR"
See the ViGedit distribution AUTHORS file\.
.sp
.SH "RESOURCES"
Get the latest version from https://launchpad\.net/vigedit
.sp
.SH "COPYING"
Copyright \(co 2006 Trond Danielsen, Copyright \(co 2008 Stephen Moore\. Free use of this software is granted under the terms of the GNU General Public License (GPL)\.
.sp
.SH "NOTES"
.IP " 1." 4
Bindings
.RS 4
\%bindings.html
.RE
.IP " 2." 4
Adding a mode
.RS 4
\%addingMode.html
.RE
